package io.vproxy.easydb;

import io.vproxy.easydb.jdbc.JDBC;
import org.junit.Before;
import org.junit.Test;

public class TestResourceLeak {
    private JDBC jdbc;

    @Before
    public void before() throws Exception {
        BeforeAll.beforeClass();
        jdbc = BeforeAll.jdbc;

        jdbc.prepare(
            "CREATE MEMORY TABLE \"test_leak\" (\n" +
            "  \"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,\n" +
            "  \"x\" INTEGER NOT NULL\n" +
            ")\n"
        ).execute();
    }

    @Test
    public void leak() {
        for (int i = 0; i < 10000; ++i) {
            //noinspection unused,EmptyTryBlock
            try (var x = jdbc.prepare("select * from \"test_leak\" where 1 = 1").query()) {
            }
        }
    }
}
